<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blockbuster</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="css/style.css">
    <link rel="shortcut icon" href="images/blockbuster-logo.png" type="image/x-icon">
</head>

<body>
      <header class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="<?= BASE_URL ?>home">🎬 Blockbuster</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="<?= BASE_URL ?>home">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<?= BASE_URL ?>genders">Géneros</a>
          </li>
        </ul>

        <ul class="navbar-nav mb-2 mb-lg-0">
          <?php if ($user): ?>
            <!-- Usuario logueado -->
            <li class="nav-item">
              <span class="nav-link text-success">
                👤 <?= htmlspecialchars($user->user) ?>
              </span>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="logout">Cerrar sesión</a>
            </li>
          <?php else: ?>
            <!-- Usuario no logueado -->
            <li class="nav-item">
              <a class="nav-link" href="showLogin">Login</a>
            </li>
          <?php endif; ?>
        </ul>
      </div>
    </div>
  </header>

  <main class="container mt-4">

 