<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    
    <!-- Custom CSS -->
    <link rel="stylesheet" href="css/style.css">
    <link rel="shortcut icon" href="images/blockbuster-logo.png" type="image/x-icon">
    <title>Blockbuster</title>
</head>

<body>
    <!-- Navbar -->
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-secondary shadow-sm">
            <div class="container-fluid">
                <a class="navbar-brand fw-bold text-warning" href="">Blockbuster</a>
                
                <!-- Botón hamburguesa -->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <!-- Menú -->
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="nav-link active" href="">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="genres">Genres</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="showList">Admin</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="showLogin">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-danger fw-semibold" href="logout">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
